@startuml

skinparam defaultFontSize 20
skinparam monochrome true

file Feature <<Gherkin>>
note bottom of Feature
    GIVEN ...
    WHEN ...
    THEN ...
end note

rectangle kapoeira <<cucumber>> #lightgrey  {
    component StepDefinitions <<Glue>>
    component Runner

    Runner -up-> StepDefinitions : USE
}
note top of kapoeira
    Fixed DSL
    **NO CODE TO WRITE!**
end note


component Execution
note bottom of Execution
    **KAFKA calls**
end note

Feature <- Runner : READ
StepDefinitions -> Execution : CALL

@enduml