name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - '**' #publish a release

env:
  SONATYPE_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      PGP_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      PGP_SECRET : ${{ secrets.GPG_SECRET }}
      GPG_OWNERTRUST : ${{ secrets.GPG_OWNERTRUST }}
      SONATYPE_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.NEXUS_USERNAME }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: Tests
        run: sbt test
      - name: Configure GPG Key
        run: |
          echo $PGP_SECRET | base64 --decode | gpg --import -v --batch
      - name: Configure GPG Ownertrust
        run: |
          echo -n "$GPG_OWNERTRUST" | base64 --decode | gpg --import-ownertrust
      - name: Release
        run: |
          sbt ci-release
