name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'feat/**' #will publish snapshots
#      - 'main' #will also publish snapshots - useful before releasing
    tags:
      - '**' #will publish a release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: Tests
        run: sbt test
      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          PGP_SECRET : ${{ secrets.GPG_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.NEXUS_USERNAME }}
